### ISSUE TITLE
Import fails when parent script frozen via pyinstaller

### ISSUE THREAD

**Issue by gberardinelli** [QuantumSpatialInc/condorize3#1]
> Traceback (most recent call last):
>   File "ieq.py", line 2, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\__init__.py", line 1, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\description\__init__.py", line 1, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\description\description.py", line 2, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\description\validation.py", line 1, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\resources\__init__.py", line 4, in <module>
>   File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in
> load_module
>   File "site-packages\condorize\resources\executables.py", line 7, in <module>
> IOError: [Errno 2] No such file or directory: 'C:\\Scripts\\ieq\\condorize\\resour
> ces\\files\\executables.json'
> Failed to execute script ieq

Might be necessary to create a hook

**Comment by gberardinelli** [comment]
Created hook
